# Deploy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploytemperatura
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: voyager123/voyager-front
          ports:
            - containerPort: 80

---

#Service
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30000
  type: LoadBalancer
